### ISSUE TITLE
Questions about how to choose a suitable lambda in this paper

### ISSUE THREAD

**Issue by HelloWorldLTY** [runopti/stg#5]
Hi, I use stg to solve my own problem about cell type classification. I find that the probability here are not closed to 0 or 1, like:
![image](https://user-images.githubusercontent.com/43333475/219544320-14dea6de-b124-452b-8c71-876c2a4c8000.png)

The prob value is very large, even if I choose very small lambda. Is choosing lambda related to the complexity of our problem? Thanks a lot.

**Comment by runopti** [comment]
If you increase the lambda value, the regularization for the gates becomes stronger, which leads to better results in general for feature selection. 
If you decrease a lambda, the regularization for the gates becomes weak, so the gate values are less likely to converge.
Having said that, if the signal-to-noise ratio is low (e.g. real world data), feature selection becomes harder even with this method, and you might not be able to see clear separation like 0 or 1.
